### ISSUE TITLE
 How to use Git Gui ??

### ISSUE THREAD

**Issue by Marcondezxp** [ih1115/BattleriteAimbot#10]
I downloaded Git Gui and the master file started working when I run it through the debug, I would like to know where the console is so I can change the character by the command

**Comment by Marcondezxp** [comment]
I downloaded Git Gui and the master file started working when I run it through the debug, I would like to know where the console is so I can change the character by the command

**Comment by ih1115** [comment]
Open up Command Prompt
run
```git clone https://github.com/ih1115/BattleriteAimbot.git```
```cd BattleriteAimbot```

now to change to Jade run
```git checkout Jade```
