### ISSUE TITLE
Window Found, but not doing anything.

### ISSUE THREAD

**Issue by Ganom** [ih1115/BattleriteAimbot#5]
https://i.imgur.com/rIvaD1B.png

Not sure why its happening, earlier compiles were working. Not sure which commit it stopped working at.

Being ran as admin as well.

**Comment by ih1115** [comment]
Since you've got it working once before, try restarting (two times to be sure) battlerite and try again because of this issue https://github.com/ih1115/BattleriteAimbot/issues/2 .

**Comment by Ganom** [comment]
Tried restarting multiple times, still the same result.

**Comment by DetectiveSquirrel** [comment]
you can keep restarting your game and rejoining a private match against bots until it starts working so you dont have to pray it works when you join a normal match.

**Comment by ih1115** [comment]
Let me know if this still doesn't work.
I did change the local player offsets to a different variant recently because of someone else earlier.
I can change it back..
Commit https://github.com/ih1115/BattleriteAimbot/commit/1779084007e01c6fb7e153874d7319cecd62d898

**Comment by Ganom** [comment]
Reverting to older commit has been successful 3/3 times ive tested so far.

**Comment by ih1115** [comment]
Reverted the offsets.
