### ISSUE TITLE
What are you supposed to run?

### ISSUE THREAD

**Issue by Principle29** [ih1115/BattleriteAimbot#6]
I downloaded the files, but do not see a .exe?

**Comment by ih1115** [comment]
Follow the ```Build``` and ```Use``` guides outlined in the ```README.md``` https://github.com/ih1115/BattleriteAimbot/

I updated it.

**Comment by Ganom** [comment]
You have to compile it yourself, if you don't know how to do that, watch a video or wait till its released.
