### ISSUE TITLE
The procedure entry point could not be located _vcrt_cleanup_type_info_names

### ISSUE THREAD

**Issue by Jhon525** [ih1115/BattleriteAimbot#9]
I already have the Microsoft Visual C++ 2015 and dll.

http://prntscr.com/hfgwxs

**Comment by ih1115** [comment]
Did you change the project settings?

**Comment by Jhon525** [comment]
I only changed the Screen resolution.

**Comment by ih1115** [comment]
And you are building under ```x86 Debug``` ?

**Comment by Jhon525** [comment]
No, worked now. Thanks!

**Comment by mitobr** [comment]
I'm having the same problem. Anyone fixed it already?
